repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Match your installed version
    hooks:
      - id: black
        args: []
        # args: ["--line-length=119", "--target-version=py311"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        # args: []
        args: ["--max-line-length", "150"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
