"""session title

Revision ID: 1fc29f4cb798
Revises: f2a3b4c5d6e7
Create Date: 2026-06-13 08:21:27.098026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1fc29f4cb798'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###
