"""removed telegram_user_id

Revision ID: b27b3ba8e7b0
Revises: d05ccfbf6422
Create Date: 2026-05-29 08:14:46.957481

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "b27b3ba8e7b0"
down_revision: Union[str, None] = "d05ccfbf6422"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "sessions", ["telegram_chat_id"])
    op.drop_column("sessions", "telegram_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("telegram_user_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "sessions", type_="unique")
    # ### end Alembic commands ###
