"""empty message

Revision ID: d05ccfbf6422
Revises: 0001
Create Date: 2026-05-29 04:58:48.278006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d05ccfbf6422"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assignments", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("assignments", sa.Column("modified_at", sa.DateTime(), nullable=True))
    op.add_column("items", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("items", sa.Column("modified_at", sa.DateTime(), nullable=True))
    op.add_column("people", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("people", sa.Column("modified_at", sa.DateTime(), nullable=True))
    op.add_column("sessions", sa.Column("modified_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("sessions", "modified_at")
    op.drop_column("people", "modified_at")
    op.drop_column("people", "created_at")
    op.drop_column("items", "modified_at")
    op.drop_column("items", "created_at")
    op.drop_column("assignments", "modified_at")
    op.drop_column("assignments", "created_at")
    # ### end Alembic commands ###
