name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: true
          script: |
            cd /srv/hsbch
            git pull https://github.com/jamshid17/hsbch main
            docker compose -f docker-compose.yml up -d --build
